# version: "3.9"
services:
  cleaner:
    build: ..
    environment:
      AWS_ACCESS_KEY_ID: foobar
      AWS_SECRET_ACCESS_KEY: foobar
      MYSQL_HOST: mysql:3306
      AWS_ENDPOINT: http://localstack:4566
    depends_on:
      mysql:
        condition: service_healthy
      localstack:
        condition: service_healthy
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
  localstack:
    extends:
      file: docker-compose.base.yml
      service: localstack
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.66.47.0/24
          gateway: 10.66.47.1
